### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mybyte** [loganstellway/self-signed-ssl#11]
Throws an error on Centos7 / standard bash:

```
createcert.sh: line 193: syntax error near unexpected token `('
createcert.sh: line 193: `  openssl req -new -sha256 -nodes -out "${OUTPATH}${FILENAME}.csr" -newkey rsa:2048 -keyout "${OUTPATH}${FILENAME}.key" -config <( cat "${tmp}/tmp.csr.cnf" )'
```

**Comment by loganstellway** [comment]
Hello,

Apologies for the late reply -
I just tested the script on a virtual machine running CentOS 7 with bash and was not able to replicate the issue. 

Are you still experiencing this?

**Comment by loganstellway** [comment]
Hi @mybyte 
Can you confirm that the latest refactored script no longer causes these issues?

**Comment by loganstellway** [comment]
Closing the issue for now - 
Please let me know if you're still experiencing the issue.
