### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by sudhir600** [loganstellway/self-signed-ssl#6]
I clone this and run bach file as ssl.bat but nothing happen.
May you help me how to use this?

**Comment by loganstellway** [comment]
Hi @sudhir600,

The repository contains a `self-signed-tls` which is an executable bash script.

1. Clone the repository
>git clone https://github.com/loganstellway/self-signed-ssl.git
2. `cd` into the downloaded folder
>cd self-signed-ssl
3. Run the executable script
>./self-signed-tls

**Comment by sudhir600** [comment]
Hi @loganstellway 

I did the same but found issue like this.

![image](https://user-images.githubusercontent.com/4952560/38659932-1fce8f7a-3e49-11e8-89b8-0a3bacea62b5.png)

**Comment by jonnott** [comment]
I'm finding that these certs don't work with Google Chrome 65 on Mac, even when the .crt is opened in Keychain Access and set to 'Always Trust' .. I'm using MAMP.

Chrome Dev Tools says "(net::ERR_CERT_COMMON_NAME_INVALID)." .. and the 'Not Secure' icon appears red in the address bar.

Domain for site is sitename.test and I'm using *.sitename.test as the common name.

**Comment by loganstellway** [comment]
@sudhir600 
Can you look at [this issue](https://stackoverflow.com/questions/39160884/cannot-generate-a-new-csr-in-git-bash#answer-39161095)?

If that solves your issue, maybe it would be a good idea to add an option to specify an `openssl` configuration file.

**Comment by loganstellway** [comment]
Hi @sudhir600,

I'm going to close this issue as I haven't heard an update. Hope you were able to figure it out!
