### ISSUE TITLE
problems making Certificate Request

### ISSUE THREAD

**Issue by tonimore** [loganstellway/self-signed-ssl#7]
I we got error while creating certificate:

```
OS: ARMBIAN 5.36 user-built Ubuntu 16.04.3 LTS 3.4.113-sun8i
OpenSSL: OpenSSL 1.0.2g  1 Mar 2016
#uname -a
Linux orangepizero 3.4.113-sun8i #4 SMP PREEMPT Wed Nov 22 13:45:28 CET 2017 armv7l armv7l armv7l GNU/Linux

```
Log:

```
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:orange.vpn
Email Address []:
Generating RSA private key, 2048 bit long modulus
..............+++
.........................................................+++
e is 65537 (0x10001)
end of string encountered while processing type of subject name element #6
problems making Certificate Request
Generating a 2048 bit RSA private key
.................................+++
.....................+++
writing new private key to './orange.vpn.key'
-----
problems making Certificate Request
3070130000:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:a_mbstr.c:151:minsize=2
./orange.vpn.csr: No such file or directory

```

**Comment by jendrusha** [comment]
Give all information like state, city, organization etc.. It should work.

**Comment by AlexDunmow** [comment]
Didn't for me.

**Comment by jvyden420** [comment]
Did this to me.

**Comment by jvyden420** [comment]
Yeah, you just need to fill out all the data.

**Comment by antonnifo** [comment]
> Didn't for me.

check the 2 letter country codes for CSR generation here
https://clients.hostingireland.ie/knowledgebase/2042/2-letter-country-codes-for-CSR-generation.html

**Comment by typo3ua** [comment]
> Give all information like state, city, organization etc

Where I have to add it?

**Comment by loganstellway** [comment]
Is this still an issue? 

I was able to successfully run the script on an [Armbian Docker container](https://hub.docker.com/r/armbian/build), but the build is much newer:

- Ubuntu `20.04.1` LTS
- OpenSSL `1.1.1f`  31 Mar 2020

I haven't used or built with Armbian before, but I would be happy to further test if anyone can point me in the right direction to create a custom build.

**Comment by tonimore** [comment]
I have tried again with Armbian based on Debian 20.08.14, no success:
```
$ ./self-signed-tls
Country Name (2 letter code) [AU]:RU
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:None
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:orange.vpn
Subject Alternative Name(s) (e.g. subdomains) []:
Email Address []:
Generating RSA private key, 2048 bit long modulus (2 primes)
...................................................................+++++
.................................+++++
e is 65537 (0x010001)
req: No value provided for Subject Attribute ST, skipped
req: No value provided for Subject Attribute L, skipped
req: No value provided for Subject Attribute OU, skipped
req: No value provided for Subject Attribute emailAddress, skipped
Generating a RSA private key
......+++++
.................................+++++
writing new private key to './orange.vpn.key'
-----
problems making Certificate Request
3069300752:error:0D07A098:asn1 encoding routines:ASN1_mbstring_ncopy:string too short:../crypto/asn1/a_mbstr.c:100:minsize=1
Can't open ./orange.vpn.csr for reading, No such file or directory
3069698064:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('./orange.vpn.csr','r')
3069698064:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
```

```
$ uname -a
Linux orangepizero 5.8.16-sunxi #20.08.14 SMP Tue Oct 20 22:15:32 CEST 2020 armv7l armv7l armv7l GNU/Linux
```

**Comment by loganstellway** [comment]
Hi @tonimore,
It looks like the following fields weren't given a value:

- State or Province Name
- Locality Name
- Organizational Unit Name
- Email Address

I assume these are required values for generating an OpenSSL certificate, but I would have to verify with some research. 
Does anybody have any insight? 

Maybe it would be helpful if the script didn't continue until values were provided for required fields?
Does anybody have any opinions?

**Comment by tonimore** [comment]
I think only CN filed is required. Because I have a few self-signed serts without  State or Province Name / Locality Name / Organizational Unit Name / Email Address fields 





On 8 Jan 2021, at 23:41, Logan Stellway <notifications@github.com> wrote:


Hi @tonimore <https://github.com/tonimore>,
It looks like the following fields weren't given a value:

State or Province Name
Locality Name
Organizational Unit Name
Email Address
I assume these are required values for generating an OpenSSL certificate, but I would have to verify with some research.
Does anybody have any insight?

Maybe it would be helpful if the script didn't continue until values were provided for required fields?
Does anybody have any opinions?

**Comment by loganstellway** [comment]
Hi all 👋
I have just reworked the script to allow for optional subject arguments. 
Here are the [related changes](https://github.com/loganstellway/self-signed-ssl/blob/4e2c02c056430ca6c880731d7a71276e2663cd39/self-signed-tls#L192-L213). 

Please feel free to give feedback on the implementation.

**Comment by loganstellway** [comment]
I'm closing this issue for now - 
Please let me know if this is still an issue for anyone.
