### ISSUE TITLE
Are Subject Alternative Names SAN supported?

### ISSUE THREAD

**Issue by felipe1982** [loganstellway/self-signed-ssl#9]
I would like my certs to support dev.example.com and test.example.com. Does this tool support this?

**Comment by loganstellway** [comment]
Hi @felipe1982 !
Just added a `--san` option to provide a comma-delimited list of Subject Alternate Names.

Here's the [commit](https://github.com/loganstellway/self-signed-ssl/commit/3551d48735c01f919ea808d4e4884a95fd1fcb17) for reference.
